// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NutriNexusAPI.Data;

#nullable disable

namespace NutriNexus.Api.Data.Migrations
{
    [DbContext(typeof(MealAppContext))]
    [Migration("20251223163647_ImgUrlToSourceUrl")]
    partial class ImgUrlToSourceUrl
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.10");

            modelBuilder.Entity("NutriNexus.Api.Entities.RecipeIngredient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("IngredientId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Note")
                        .HasColumnType("TEXT");

                    b.Property<float?>("Quantity")
                        .HasColumnType("REAL");

                    b.Property<int>("RecipeId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("IngredientId");

                    b.HasIndex("RecipeId");

                    b.ToTable("RecipeIngredients");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IngredientId = 1,
                            Note = "softned",
                            Quantity = 1f,
                            RecipeId = 1,
                            Unit = "cup"
                        },
                        new
                        {
                            Id = 2,
                            IngredientId = 2,
                            Quantity = 1f,
                            RecipeId = 1,
                            Unit = "cup"
                        },
                        new
                        {
                            Id = 3,
                            IngredientId = 3,
                            Note = "packed",
                            Quantity = 1f,
                            RecipeId = 1,
                            Unit = "cup"
                        },
                        new
                        {
                            Id = 4,
                            IngredientId = 4,
                            Quantity = 2f,
                            RecipeId = 1,
                            Unit = "tsp"
                        },
                        new
                        {
                            Id = 5,
                            IngredientId = 5,
                            Quantity = 2f,
                            RecipeId = 1,
                            Unit = "large"
                        },
                        new
                        {
                            Id = 6,
                            IngredientId = 6,
                            Quantity = 3f,
                            RecipeId = 1,
                            Unit = "cup"
                        },
                        new
                        {
                            Id = 7,
                            IngredientId = 7,
                            Quantity = 1f,
                            RecipeId = 1,
                            Unit = "tsp"
                        },
                        new
                        {
                            Id = 8,
                            IngredientId = 8,
                            Quantity = 0.5f,
                            RecipeId = 1,
                            Unit = "tsp"
                        },
                        new
                        {
                            Id = 9,
                            IngredientId = 9,
                            Quantity = 1f,
                            RecipeId = 1,
                            Unit = "tsp"
                        },
                        new
                        {
                            Id = 10,
                            IngredientId = 10,
                            Note = "12 oz",
                            Quantity = 1f,
                            RecipeId = 1,
                            Unit = "cup"
                        });
                });

            modelBuilder.Entity("NutriNexusAPI.Entities.Equipment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Equipment");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Standard measuring spoons",
                            Name = "measuring spoons",
                            SourceUrl = "https://amzlink.to/az0Tmz0p6RGTA"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Dry measuring cups",
                            Name = "measuring cups",
                            SourceUrl = "https://amzlink.to/az0DjP0Sx7AVd"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Hand or stand mixer",
                            Name = "electric mixer",
                            SourceUrl = "https://amzlink.to/az04r9lAhaKsP"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Rubber spatula for mixing",
                            Name = "spatula",
                            SourceUrl = "https://amzlink.to/az0cHANfPnAKd"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Standard baking sheet",
                            Name = "baking sheet",
                            SourceUrl = "https://amzlink.to/az0h3VEQB4BtJ"
                        },
                        new
                        {
                            Id = 6,
                            Description = "For lining baking sheets",
                            Name = "parchment paper",
                            SourceUrl = "https://amzlink.to/az0e1HAvwbn07"
                        },
                        new
                        {
                            Id = 7,
                            Description = "for scooping cookies",
                            Name = "cookie scoop",
                            SourceUrl = "https://amzlink.to/az0935VbND2Ud"
                        },
                        new
                        {
                            Id = 8,
                            Description = "silicone baking mat",
                            Name = "silicone baking mat",
                            SourceUrl = "https://amzlink.to/az0tZruG7esod"
                        },
                        new
                        {
                            Id = 9,
                            Description = "for mixing",
                            Name = "hand mixer",
                            SourceUrl = "https://amzlink.to/az0GGY6pRrF4W"
                        });
                });

            modelBuilder.Entity("NutriNexusAPI.Entities.Ingredient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<float?>("Calories")
                        .HasColumnType("REAL");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Ingredients");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Calories = 40f,
                            Name = "salted butter"
                        },
                        new
                        {
                            Id = 2,
                            Calories = 40f,
                            Name = "granulated sugar"
                        },
                        new
                        {
                            Id = 3,
                            Calories = 40f,
                            Name = "light brown sugar"
                        },
                        new
                        {
                            Id = 4,
                            Calories = 40f,
                            Name = "pure vanilla extract"
                        },
                        new
                        {
                            Id = 5,
                            Calories = 40f,
                            Name = "egg"
                        },
                        new
                        {
                            Id = 6,
                            Calories = 40f,
                            Name = "all-purpose flour"
                        },
                        new
                        {
                            Id = 7,
                            Calories = 40f,
                            Name = "baking soda"
                        },
                        new
                        {
                            Id = 8,
                            Calories = 40f,
                            Name = "baking powder"
                        },
                        new
                        {
                            Id = 9,
                            Calories = 40f,
                            Name = "sea salt"
                        },
                        new
                        {
                            Id = 10,
                            Calories = 40f,
                            Name = "chocolate chips"
                        });
                });

            modelBuilder.Entity("NutriNexusAPI.Entities.Recipe", b =>
                {
                    b.Property<int>("RecipeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Calories")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Carbs")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CookTime")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Course")
                        .HasColumnType("TEXT");

                    b.Property<string>("Cuisine")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Fat")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("PrepTime")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Protein")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Rating")
                        .HasColumnType("TEXT");

                    b.Property<int>("ServingSize")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TotalTime")
                        .HasColumnType("INTEGER");

                    b.HasKey("RecipeId");

                    b.ToTable("Recipes");

                    b.HasData(
                        new
                        {
                            RecipeId = 1,
                            Calories = 100,
                            Carbs = 100,
                            CookTime = 8,
                            Course = "Dessert",
                            Cuisine = "American",
                            Description = "This is the best chocolate chip cookie recipe ever. No funny ingredients, no chilling time, etc. Just a simple, straightforward, amazingly delicious, doughy yet still fully cooked, chocolate chip cookie that turns out perfectly every single time!",
                            Fat = 100,
                            ImageUrl = "/chocolate-chip-cookie.jpg",
                            Name = "The Best Chocolate Chip Cookie Recipe Ever",
                            PrepTime = 10,
                            Protein = 100,
                            Rating = 4.99m,
                            ServingSize = 36,
                            TotalTime = 30
                        });
                });

            modelBuilder.Entity("NutriNexusAPI.Entities.RecipeEquipment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("EquipmentId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Quantity")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RecipeId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("EquipmentId");

                    b.HasIndex("RecipeId");

                    b.ToTable("RecipeEquipment");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            EquipmentId = 1,
                            Quantity = 1,
                            RecipeId = 1
                        },
                        new
                        {
                            Id = 2,
                            EquipmentId = 2,
                            Quantity = 1,
                            RecipeId = 1
                        },
                        new
                        {
                            Id = 3,
                            EquipmentId = 3,
                            Notes = "The Kitchen Aid is a very popular mizer",
                            Quantity = 1,
                            RecipeId = 1
                        },
                        new
                        {
                            Id = 4,
                            EquipmentId = 4,
                            Quantity = 1,
                            RecipeId = 1
                        },
                        new
                        {
                            Id = 5,
                            EquipmentId = 5,
                            Quantity = 3,
                            RecipeId = 1
                        },
                        new
                        {
                            Id = 6,
                            EquipmentId = 6,
                            Quantity = 1,
                            RecipeId = 1
                        },
                        new
                        {
                            Id = 7,
                            EquipmentId = 7,
                            Quantity = 1,
                            RecipeId = 1
                        },
                        new
                        {
                            Id = 8,
                            EquipmentId = 8,
                            Quantity = 1,
                            RecipeId = 1
                        },
                        new
                        {
                            Id = 9,
                            EquipmentId = 9,
                            Quantity = 1,
                            RecipeId = 1
                        });
                });

            modelBuilder.Entity("NutriNexusAPI.Entities.RecipeInstruction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Instruction")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("RecipeId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StepNumber")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("RecipeId");

                    b.ToTable("RecipeInstructions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Instruction = "Preheat oven to 375 degrees Fahrenheit (190 degrees Celsius). Line three baking sheets with parchment paper and set aside.",
                            RecipeId = 1,
                            StepNumber = 1
                        },
                        new
                        {
                            Id = 2,
                            Instruction = "In a medium bowl mix flour, baking soda, baking powder and salt. Set aside.",
                            RecipeId = 1,
                            StepNumber = 2
                        },
                        new
                        {
                            Id = 3,
                            Instruction = "Cream together butter and sugars until combined.",
                            RecipeId = 1,
                            StepNumber = 3
                        },
                        new
                        {
                            Id = 4,
                            Instruction = "Beat in eggs and vanilla until light (about 1 minute).",
                            RecipeId = 1,
                            StepNumber = 4
                        },
                        new
                        {
                            Id = 5,
                            Instruction = "Mix in the dry ingredients until combined.",
                            RecipeId = 1,
                            StepNumber = 5
                        },
                        new
                        {
                            Id = 6,
                            Instruction = "Add chocolate chips and mix well.",
                            RecipeId = 1,
                            StepNumber = 6
                        },
                        new
                        {
                            Id = 7,
                            Instruction = "Roll 2-3 Tablespoons (depending on how large you like your cookies) of dough at a time into balls and place them evenly spaced on your prepared cookie sheets. ",
                            RecipeId = 1,
                            StepNumber = 7
                        },
                        new
                        {
                            Id = 8,
                            Instruction = "Bake in preheated oven for approximately 8-10 minutes. Take them out when they are just barely starting to turn brown.",
                            RecipeId = 1,
                            StepNumber = 8
                        },
                        new
                        {
                            Id = 9,
                            Instruction = "Let them sit on the baking pan for 5 minutes before removing to cooling rack.",
                            RecipeId = 1,
                            StepNumber = 9
                        });
                });

            modelBuilder.Entity("NutriNexus.Api.Entities.RecipeIngredient", b =>
                {
                    b.HasOne("NutriNexusAPI.Entities.Ingredient", "Ingredient")
                        .WithMany()
                        .HasForeignKey("IngredientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NutriNexusAPI.Entities.Recipe", "Recipe")
                        .WithMany("RecipeIngredients")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ingredient");

                    b.Navigation("Recipe");
                });

            modelBuilder.Entity("NutriNexusAPI.Entities.RecipeEquipment", b =>
                {
                    b.HasOne("NutriNexusAPI.Entities.Equipment", "Equipment")
                        .WithMany("RecipeEquipments")
                        .HasForeignKey("EquipmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NutriNexusAPI.Entities.Recipe", "Recipe")
                        .WithMany("RecipeEquipment")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Equipment");

                    b.Navigation("Recipe");
                });

            modelBuilder.Entity("NutriNexusAPI.Entities.RecipeInstruction", b =>
                {
                    b.HasOne("NutriNexusAPI.Entities.Recipe", null)
                        .WithMany("RecipeInstructions")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("NutriNexusAPI.Entities.Equipment", b =>
                {
                    b.Navigation("RecipeEquipments");
                });

            modelBuilder.Entity("NutriNexusAPI.Entities.Recipe", b =>
                {
                    b.Navigation("RecipeEquipment");

                    b.Navigation("RecipeIngredients");

                    b.Navigation("RecipeInstructions");
                });
#pragma warning restore 612, 618
        }
    }
}
