// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NutriNexusAPI.Data;

#nullable disable

namespace NutriNexusAPI.Data.Migrations
{
    [DbContext(typeof(MealAppContext))]
    [Migration("20251221235342_AddGroceryList")]
    partial class AddGroceryList
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.10");

            modelBuilder.Entity("NutriNexus.Api.Entities.RecipeIngredient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<float>("Amount")
                        .HasColumnType("REAL");

                    b.Property<float>("Calories")
                        .HasColumnType("REAL");

                    b.Property<int>("IngredientId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RecipeId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UnitId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("RecipeId");

                    b.ToTable("RecipeIngredient");
                });

            modelBuilder.Entity("NutriNexusAPI.Entities.Ingredient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<float>("Amount")
                        .HasColumnType("REAL");

                    b.Property<float>("Calories")
                        .HasColumnType("REAL");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<int>("RecipeId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UnitId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Ingredients");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Amount = 1f,
                            Calories = 34.9f,
                            Name = "salted butter",
                            RecipeId = 1,
                            UnitId = 1
                        },
                        new
                        {
                            Id = 2,
                            Amount = 1f,
                            Calories = 34.9f,
                            Name = "granulated sugar",
                            RecipeId = 1,
                            UnitId = 1
                        },
                        new
                        {
                            Id = 3,
                            Amount = 1f,
                            Calories = 34.9f,
                            Name = "light brown sugar",
                            RecipeId = 1,
                            UnitId = 1
                        },
                        new
                        {
                            Id = 4,
                            Amount = 1f,
                            Calories = 34.9f,
                            Name = "pure vanilla extract",
                            RecipeId = 1,
                            UnitId = 1
                        },
                        new
                        {
                            Id = 5,
                            Amount = 2f,
                            Calories = 34.9f,
                            Name = "egg",
                            RecipeId = 1,
                            UnitId = 2
                        },
                        new
                        {
                            Id = 6,
                            Amount = 3f,
                            Calories = 34.9f,
                            Name = "all-purpose flour",
                            RecipeId = 1,
                            UnitId = 1
                        },
                        new
                        {
                            Id = 7,
                            Amount = 1f,
                            Calories = 34.9f,
                            Name = "baking soda",
                            RecipeId = 1,
                            UnitId = 3
                        },
                        new
                        {
                            Id = 8,
                            Amount = 0.5f,
                            Calories = 34.9f,
                            Name = "baking powder",
                            RecipeId = 1,
                            UnitId = 3
                        },
                        new
                        {
                            Id = 9,
                            Amount = 1f,
                            Calories = 34.9f,
                            Name = "sea salt",
                            RecipeId = 1,
                            UnitId = 3
                        },
                        new
                        {
                            Id = 10,
                            Amount = 2f,
                            Calories = 34.9f,
                            Name = "chocolate chips",
                            RecipeId = 1,
                            UnitId = 1
                        });
                });

            modelBuilder.Entity("NutriNexusAPI.Entities.Recipe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Calories")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Carbs")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CookTime")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Course")
                        .HasColumnType("TEXT");

                    b.Property<string>("Cuisine")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.PrimitiveCollection<string>("Directions")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Fat")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("PrepTime")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Protein")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Rating")
                        .HasColumnType("TEXT");

                    b.Property<int>("ServingSize")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TotalTime")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Recipes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Calories = 100,
                            Carbs = 100,
                            CookTime = 8,
                            Course = "Dessert",
                            Cuisine = "American",
                            Description = "This is the best chocolate chip cookie recipe ever. No funny ingredients, no chilling time, etc. Just a simple, straightforward, amazingly delicious, doughy yet still fully cooked, chocolate chip cookie that turns out perfectly every single time!",
                            Directions = "[\"cookie 1\",\"cookie 2\",\"cookie 3\"]",
                            Fat = 100,
                            ImageUrl = "/chocolate-chip-cookie.jpg",
                            Name = "The Best Chocolate Chip Cookie Recipe Ever",
                            PrepTime = 10,
                            Protein = 100,
                            Rating = 4.99m,
                            ServingSize = 36,
                            TotalTime = 30
                        });
                });

            modelBuilder.Entity("NutriNexusAPI.Entities.Unit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Unit");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "cup"
                        },
                        new
                        {
                            Id = 2,
                            Name = "egg"
                        },
                        new
                        {
                            Id = 3,
                            Name = "tsp"
                        });
                });

            modelBuilder.Entity("NutriNexus.Api.Entities.RecipeIngredient", b =>
                {
                    b.HasOne("NutriNexusAPI.Entities.Recipe", null)
                        .WithMany("Ingredients")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("NutriNexusAPI.Entities.Recipe", b =>
                {
                    b.Navigation("Ingredients");
                });
#pragma warning restore 612, 618
        }
    }
}
