// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NutriNexusAPI.Data;

#nullable disable

namespace NutriNexusAPI.Data.Migrations
{
    [DbContext(typeof(MealAppContext))]
    [Migration("20251220172912_DataAnnotations")]
    partial class DataAnnotations
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.10");

            modelBuilder.Entity("NutriNexusAPI.Entities.Direction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("RecipeId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StepNumber")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("RecipeId");

                    b.ToTable("Directions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Preheat oven to 375 degrees Fahrenheit (190 degrees Celsius). Line three baking sheets with parchment paper and set aside.",
                            RecipeId = 1,
                            StepNumber = 1
                        },
                        new
                        {
                            Id = 2,
                            Description = "In a medium bowl mix flour, baking soda, baking powder and salt. Set aside.",
                            RecipeId = 1,
                            StepNumber = 2
                        },
                        new
                        {
                            Id = 3,
                            Description = "Cream together butter and sugars until combined.",
                            RecipeId = 1,
                            StepNumber = 3
                        });
                });

            modelBuilder.Entity("NutriNexusAPI.Entities.Equipment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<int>("RecipeId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Equipment");
                });

            modelBuilder.Entity("NutriNexusAPI.Entities.Ingredient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<float>("Amount")
                        .HasColumnType("REAL");

                    b.Property<float>("Calories")
                        .HasColumnType("REAL");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<int>("RecipeId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UnitId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("RecipeId");

                    b.ToTable("Ingredients");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Amount = 1f,
                            Calories = 34.9f,
                            Name = "salted butter",
                            RecipeId = 1,
                            UnitId = 1
                        },
                        new
                        {
                            Id = 2,
                            Amount = 1f,
                            Calories = 34.9f,
                            Name = "granulated sugar",
                            RecipeId = 1,
                            UnitId = 1
                        },
                        new
                        {
                            Id = 3,
                            Amount = 1f,
                            Calories = 34.9f,
                            Name = "light brown sugar",
                            RecipeId = 1,
                            UnitId = 1
                        },
                        new
                        {
                            Id = 4,
                            Amount = 1f,
                            Calories = 34.9f,
                            Name = "pure vanilla extract",
                            RecipeId = 1,
                            UnitId = 1
                        },
                        new
                        {
                            Id = 5,
                            Amount = 2f,
                            Calories = 34.9f,
                            Name = "egg",
                            RecipeId = 1,
                            UnitId = 2
                        },
                        new
                        {
                            Id = 6,
                            Amount = 3f,
                            Calories = 34.9f,
                            Name = "all-purpose flour",
                            RecipeId = 1,
                            UnitId = 1
                        },
                        new
                        {
                            Id = 7,
                            Amount = 1f,
                            Calories = 34.9f,
                            Name = "baking soda",
                            RecipeId = 1,
                            UnitId = 3
                        },
                        new
                        {
                            Id = 8,
                            Amount = 0.5f,
                            Calories = 34.9f,
                            Name = "baking powder",
                            RecipeId = 1,
                            UnitId = 3
                        },
                        new
                        {
                            Id = 9,
                            Amount = 1f,
                            Calories = 34.9f,
                            Name = "sea salt",
                            RecipeId = 1,
                            UnitId = 3
                        },
                        new
                        {
                            Id = 10,
                            Amount = 2f,
                            Calories = 34.9f,
                            Name = "chocolate chips",
                            RecipeId = 1,
                            UnitId = 1
                        });
                });

            modelBuilder.Entity("NutriNexusAPI.Entities.NutritionFact", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("NutritionFactCategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RecipeId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Value")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("RecipeId");

                    b.ToTable("NutritionFacts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            NutritionFactCategoryId = 1,
                            RecipeId = 1,
                            Value = 183
                        },
                        new
                        {
                            Id = 2,
                            NutritionFactCategoryId = 2,
                            RecipeId = 1,
                            Value = 8
                        },
                        new
                        {
                            Id = 3,
                            NutritionFactCategoryId = 3,
                            RecipeId = 1,
                            Value = 26
                        },
                        new
                        {
                            Id = 4,
                            NutritionFactCategoryId = 4,
                            RecipeId = 1,
                            Value = 2
                        });
                });

            modelBuilder.Entity("NutriNexusAPI.Entities.NutritionFactCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("NutritionFactCategories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Calories"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Fat"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Carbs"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Protein"
                        });
                });

            modelBuilder.Entity("NutriNexusAPI.Entities.Recipe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CookTime")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Course")
                        .HasColumnType("TEXT");

                    b.Property<string>("Cuisine")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("PrepTime")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Rating")
                        .HasColumnType("TEXT");

                    b.Property<int>("ServingSize")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TotalTime")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Recipes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CookTime = 8,
                            Course = "Dessert",
                            Cuisine = "American",
                            Description = "This is the best chocolate chip cookie recipe ever. No funny ingredients, no chilling time, etc. Just a simple, straightforward, amazingly delicious, doughy yet still fully cooked, chocolate chip cookie that turns out perfectly every single time!",
                            ImageUrl = "/chocolate-chip-cookie.jpg",
                            Name = "The Best Chocolate Chip Cookie Recipe Ever",
                            PrepTime = 10,
                            Rating = 4.99m,
                            ServingSize = 36,
                            TotalTime = 30
                        });
                });

            modelBuilder.Entity("NutriNexusAPI.Entities.RecipeStep", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("RecipeId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("RecipeSteps");
                });

            modelBuilder.Entity("NutriNexusAPI.Entities.Unit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Units");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "cup"
                        },
                        new
                        {
                            Id = 2,
                            Name = "egg"
                        },
                        new
                        {
                            Id = 3,
                            Name = "tsp"
                        });
                });

            modelBuilder.Entity("NutriNexusAPI.Entities.Direction", b =>
                {
                    b.HasOne("NutriNexusAPI.Entities.Recipe", null)
                        .WithMany("Directions")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("NutriNexusAPI.Entities.Ingredient", b =>
                {
                    b.HasOne("NutriNexusAPI.Entities.Recipe", null)
                        .WithMany("Ingredients")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("NutriNexusAPI.Entities.NutritionFact", b =>
                {
                    b.HasOne("NutriNexusAPI.Entities.Recipe", null)
                        .WithMany("NutritionFacts")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("NutriNexusAPI.Entities.Recipe", b =>
                {
                    b.Navigation("Directions");

                    b.Navigation("Ingredients");

                    b.Navigation("NutritionFacts");
                });
#pragma warning restore 612, 618
        }
    }
}
