@NutriNexus.Api_HostAddress = http://localhost:5125

GET {{NutriNexus.Api_HostAddress}}/weatherforecast/
Accept: application/json

###
GET http://localhost:5125/meals/

###
GET http://0.0.0.0:8080/


###
GET http://0.0.0.0:8080/