// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NutriNexusAPI.Data;

#nullable disable

namespace NutriNexusAPI.Data.Migrations
{
    [DbContext(typeof(MealAppContext))]
    [Migration("20251023234641_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.9");

            modelBuilder.Entity("NutriNexusAPI.Entities.Recipe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ServingSize")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TimeEstimate")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Recipes");
                });

            modelBuilder.Entity("NutriNexusAPI.Entities.RecipeStep", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("RecipeId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("RecipeId");

                    b.ToTable("RecipeSteps");
                });

            modelBuilder.Entity("NutriNexusAPI.Entities.RecipeStep", b =>
                {
                    b.HasOne("NutriNexusAPI.Entities.Recipe", null)
                        .WithMany("RecipeSteps")
                        .HasForeignKey("RecipeId");
                });

            modelBuilder.Entity("NutriNexusAPI.Entities.Recipe", b =>
                {
                    b.Navigation("RecipeSteps");
                });
#pragma warning restore 612, 618
        }
    }
}
