GET http://localhost:5279/meals/

### 

GET http://localhost:5279/games/

###

GET http://localhost:5279/games/5

###

POST http://localhost:5279/games
Content-Type: application/json

{
	"name": "Bauldurs Gate",
	"genreId": 2,
	"price": 19.99,
	"releaseDate": "2011-11-18"
}

###
POST http://localhost:5279/meals/
Content-Type: application/json

{
	"name": "Bread",
	"steps": [
		{"description": "get the dough"},
		{"description": "cook it"}
	]
}

###
PUT http://localhost:5279/games/5
Content-Type: application/json

{
	"name": "Minecraft",
	"genreId": 1,
	"price": 19.99,
	"releaseDate": "2011-11-18"
}

###
DELETE http://localhost:5279/games/2
